version: "2.24.5"
services:
  expressappts_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: dev
    container_name: expressappts_dev_c
    ports:
      - '8000:9000'
    image: expressappts_dev:v1
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
      # named volume wont be used
      # - ./node_modules:/app/node_modules
      # anonymous volume will be used because of bcrypt issues
      - /app/node_modules
  expressappts_live:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: live
    container_name: expressappts_live_c
    ports:
      - '8080:9000'
    image: expressappts_live:v1
    environment:
      - NODE_ENV=live