version: "2.24.5"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: dev
    container_name: devts_c
    ports:
      - '8000:9000'
    image: dev:ts
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
  live:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: live
    container_name: livets_c
    ports:
      - '8080:9000'
    image: live:ts
    environment:
      - NODE_ENV=live