version: "2.24.5"
services:
  development:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: dev_c
    ports:
      - '3000:8080'
    image: development:latest
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
  production:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: prod_c
    ports:
      - '8000:8080'
    image: production:latest