version: "2.24.5"
services:
  expressappjs_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: dev
    container_name: expressappjs_dev_c
    ports:
      - '8000:8080'
    image: expressappjs_dev:v1
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
      # named volume wont be used
      # - ./node_modules:/app/node_modules
      # anonymous volume will be used because of bcrypt issues
      - /app/node_modules
  expressappjs_live:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: live
    container_name: expressappjs_live_c
    ports:
      - '9000:8080'
    image: expressappjs_live:v1
    environment:
      - NODE_ENV=live